### ISSUE TITLE
Marketplace Info

### ISSUE THREAD

**Issue by pwp333** [oci-quickstart/oci-aviatrix#3]
title: "Aviatrix Secure Networking Platform"
description: "Multi-Cloud Cross-Region Aviatrix Controller (PayAsYouGo version)"
schemaVersion: 1.1.0
version: "20190926"
locale: "en"
logoUrl: "https://partner.cloudmarketplace.oracle.com/partner/content?contentId=63096723"
source:
  type: marketplace
  reference: 63096723

Variables to show:
[Compute]
shape
ssh_public_key

[network]
VCN
availability domain
SUBNET (public only)

**Comment by lucassrg** [comment]
@pwp333 , I pushed code for ORM/Marketplace Stack based on BYOL image.
Still pending documentation with steps.
But basically steps for testing the Stack on OCI ORM is:

- run [build_mkpl_byol.sh](https://github.com/oci-quickstart/oci-aviatrix/blob/master/controller/marketplace/util/build_mkpl_byol.sh) shell script to generate zip file
- Go to OCI console - Resource Manager service
- Create a new Stack -> Upload the file
- Fill out Variables page (specified by [marketplace.yaml](https://github.com/oci-quickstart/oci-aviatrix/blob/master/controller/marketplace/byol/marketplace.yaml)
- Save Stack
- Run Plan/Apply job similar to Terraform CLI
